version: '3.8'

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: coding_platform
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/coding_platform
    depends_on:
      - db
    
volumes:
  mariadb_data:
